name: build

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1

      - run: pip install wheel twine
      - run: poetry build
      - run: twine check dist/*

  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1
        with:
          extras: docs

      - name: build docs
        run: make -C docs html
